"""Agregada tabla Rutas_eventos

Revision ID: 2850d8525158
Revises: 5275d0b6ac4e
Create Date: 2024-12-22 18:48:05.814542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2850d8525158'
down_revision = '5275d0b6ac4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rutas_eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ruta_id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.ForeignKeyConstraint(['ruta_id'], ['rutas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rutas_eventos')
    # ### end Alembic commands ###
