"""Añade modelo Eventos

Revision ID: 5275d0b6ac4e
Revises: e19486996c51
Create Date: 2024-12-22 18:23:30.979837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5275d0b6ac4e'
down_revision = 'e19486996c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('detalles', sa.JSON(), nullable=True),
    sa.Column('tipo', sa.String(length=120), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('rutas_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['rutas_id'], ['rutas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('titulo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventos')
    # ### end Alembic commands ###
