"""Add Favorites table

Revision ID: 6ce1ffd47ede
Revises: 2850d8525158
Create Date: 2024-12-22 19:05:13.460096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ce1ffd47ede'
down_revision = '2850d8525158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rutas_id', sa.Integer(), nullable=True),
    sa.Column('eventos_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['eventos_id'], ['eventos.id'], ),
    sa.ForeignKeyConstraint(['rutas_id'], ['rutas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
