"""empty message

Revision ID: e19486996c51
Revises: 48d36beb1be6
Create Date: 2024-12-21 16:48:24.048709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19486996c51'
down_revision = '48d36beb1be6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categoria')
    )
    op.create_table('rutas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('detalles', sa.JSON(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creada', sa.Date(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('titulo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rutas')
    op.drop_table('categorias')
    # ### end Alembic commands ###
